### ISSUE TITLE
Investigate whether this is a good tool to use to add CSS and JS config too?

### ISSUE THREAD

**Issue by mattstauffer** [tighten/duster#1]

**Comment by Gummibeer** [comment]
Eslint for example can work the same - you should only have proper exclude/ignore lists for npm/composer.
Prettier could also be called from a custom binary.

**Comment by mattstauffer** [comment]
Note to see a conversationabout exactly what we should publish for the Tighten preference:

https://github.com/tighten/configs/issues/2

**Comment by driftingly** [comment]
Closing for now. This can currently be accomplished through the Duster config.
In the future, we may add opt-in configs for prettier/eslint.
