### ISSUE TITLE
Exclude parameter in duster.json not working with GLOB pattern

### ISSUE THREAD

**Issue by brdv** [tighten/duster#101]
Hi All,

First of all, very nice tool. Combining all of the various PHP code stylers together is awesome.

## Problem 
I've been trying to migrate our old setup to duster but can't get our GLOB pattern matching to work.

Let's say I have these files:
path/to/folderToExclude/index.php
path/to/folderToExclude/helper.php
path/to/folderToExclude/db.php

With the following exclude block (including glob), I'd expect all files to be excluded from duster:
```json
// snippet from duster.json in root of project
"exclude": [
        "**/folderToExclude/**"
    ],
```

When I run duster, however, it runs over all of the files listed above. I've tried a couple of variations and only the following seems to work (with exact path to a folder):
```json
// snippet from duster.json in root of project
"exclude": [
        "path/to/folderToExclude/"
    ],
```

## Question

Is this behaviour intended or am I doing something wrong?

**Comment by driftingly** [comment]
The exclude option gets passed to each tool; I'm unsure about GLOB support. 
One way to add support for this is to convert the GLOB pattern to an array of files before passing it to each tool.

**Comment by brdv** [comment]
Checked this with Pint. It does indeed not support GLOB. I'll open an issue there.
