### ISSUE TITLE
Tighten/custom_ordered_class_elements ordering question

### ISSUE THREAD

**Issue by devNoiseConsulting** [tighten/duster#102]
For the Tighten/custom_ordered_class_elements rule is it just supposed to order the element types together? Or should it also be ordering/sorting the elements within a type as well? 

Ran Duster on some code and it moved all the "public function"s together as well the "protected function"s together. While the element types got ordered together they kept the original ordering they had before the "fix".  For example, the code had a "public function flush()" towards the bottom of the code. When it was ordered/moved to be with the other "public function"s, it was placed at the end of them. Kind of expected the "public function"s to be ordered by name. 

Thanks for any feedback on this.

**Comment by driftingly** [comment]
It just orders the types/visibility together.  Controller public methods are ordered by function, not by name:

- index
- create
- store
- show
- edit
- update
- destroy

Other classes can be ordered in a way that makes sense for the specific class.
