### ISSUE TITLE
--dirty flag gets stuck

### ISSUE THREAD

**Issue by nikolaos-spyratos** [tighten/duster#105]
On PHP 8.2.4 and latest Duster, using `--dirty` seems to get stuck:
![Screenshot from 2023-04-08 14-40-05](https://user-images.githubusercontent.com/17888779/230721613-e2a0429e-6fc7-4798-9add-dc1703a2b760.png)

Not sure if this is related to #96, didn't think so since it's not running at all instead of not processing anything.

I definitely have dirty files in the current context. Running without the dirty flag processes them just fine.

**Comment by nikolaos-spyratos** [comment]
Tried again just letting it run until it hopefully hit some error or died and got this:

![Screenshot from 2023-04-08 23-55-45](https://user-images.githubusercontent.com/17888779/230744172-576c7e88-9f3e-4216-8c12-65ce0f2efeb3.png)

**Comment by driftingly** [comment]
Thanks. Gives a starting point for digging.

**Comment by dellacagna** [comment]
I started experiencing the above after upgrading from Laravel 8 to 10.

**Comment by driftingly** [comment]
@nikolaos-spyratos @dellacagna Try the latest release.

**Comment by nikspyratos** [comment]
Works perfectly now :+1:
