### ISSUE TITLE
Tlint configuration is ignored on fix

### ISSUE THREAD

**Issue by Bottelet** [tighten/duster#106]
I am currently facing an issue while trying to run Duster with a specific Tlint configuration. I have noticed that this configuration only seems to work during Lint operations and does not display any errors. However, when running fix, it ignores the configuration and changes all views from `$view->with('var', $foo)` to `view(..., ['var' => $foo])`. Although I prefer the latter, I have a challenge with this approach since it adds all the parameters on a single line, making it difficult to read when dealing with more than four-ish variables, is there any way to make a new line instead?

The Tlint configuration:
```
tlint.json
{
    "preset": "laravel",
    "disabled": ["ArrayParametersOverViewWith"]
}
```
Could you please provide guidance on how to resolve this issue?

Thanks in advance.

**Comment by driftingly** [comment]
Hi @Bottelet, 

The format command requires a different config file:

```
tformat.json
{
    "preset": "laravel",
    "disabled": ["ArrayParametersOverViewWith"]
}
```

I'm sure these can be combined into a single config file; you'll have to use both for now.

**Comment by driftingly** [comment]
https://github.com/tighten/tlint/pull/337

**Comment by Bottelet** [comment]
Thanks @driftingly !

**Comment by johnbacon** [comment]
I don't know if `tformat.json` was reintroduced, but I had to add it for `fix` to work as-desired.

**Comment by driftingly** [comment]
The updated TLint needs to be released and pulled into Duster. 
I'll be updating everything soon to pull in updated Pint configurations as well.
