### ISSUE TITLE
Duster Tlint & PHP Code sniffer are working in Gihub action but not on terminal

### ISSUE THREAD

**Issue by sandeshjangam** [tighten/duster#110]
### Config

- PHP - 8.1.18
- Composer - 2.5.5

### Problem
In the terminal, it looks like Tlint and PHP Code sniffer simply skip all the files. But in the Gihub action, it shows all the linting errors.

### Here is a terminal screenshot. Check the 1st two commands. Empty run no errors.

![image](https://user-images.githubusercontent.com/15683894/236819598-773d8080-4726-45e3-982d-ea03d680d625.png)

### Here is Github Action. You can see that there are lint errors
![image](https://user-images.githubusercontent.com/15683894/236820129-e8b88369-9240-4887-87e8-1bd93d7b9717.png)

I tried to run it on another 2 Macs. It is working on 1 Mac and the same empty things as me on another Mac. Configuration is the same across systems. Do let me know if you need more information.

**Comment by sandeshjangam** [comment]
I found the root cause of the issue

I have the Laravel application in the `public` folder and the following code in the command is skipping the files because we have used `strpos` for `public `word in the whole URL. As it is blacklisted so it's skipping the files

Refer isBlacklisted function
https://github.com/tighten/tlint/blob/main/src/Commands/BaseCommand.php#L103


Any solution to fix this?

**Comment by sandeshjangam** [comment]
@driftingly 

I think, I found the root cause of the issue

I have the Laravel application in the `public` folder and the following code in the command is skipping the files because we have used `strpos` for `public `word in the whole URL. As it is blacklisted so it's skipping the files

Refer isBlacklisted function
https://github.com/tighten/tlint/blob/main/src/Commands/BaseCommand.php#L103


Any solution to fix this?

**Comment by mattstauffer** [comment]
Fixed in #339.
