### ISSUE TITLE
Custom rules?

### ISSUE THREAD

**Issue by mohammed-alfarra** [tighten/duster#113]
Is there any support nearby for add custom rules?
Because I want to create new rule that can add missing type hints to functions and arguments like the ones that I was using in Rector

**Comment by driftingly** [comment]
Hi @mohammed-alfarra,

You can add custom PHP_CodeSniffer and PHP CS Fixer rules by providing a config for each tool.

https://github.com/tighten/duster#php_codesniffer
https://github.com/tighten/duster#php-cs-fixer

You could also configure Duster to run Rector using the `scripts` key in the Duster config: https://github.com/tighten/duster#customizing

**Comment by mohammed-alfarra** [comment]
I tried to use Rector 

**.duster.json**
`"scripts": {
        "fix": {
            "rector": ["./vendor/bin/rector", "process"]
        }
    }`
    
But I always get this error
![image](https://github.com/tighten/duster/assets/21202883/05642d85-1ea2-44aa-9c32-431a28774f3c)

**Comment by driftingly** [comment]
I just checked locally, and it's working for me.  If you're on version 1.0 of Duster try upgrading to 2.0

**Comment by TapanDerasari** [comment]
I can confirm the same error in the terminal for the latest version too (2.0.1) while running the customize duster tool

![image](https://github.com/tighten/duster/assets/41634687/6ce995ff-37ca-41ee-b3e6-7f318fe959e9)

**Comment by driftingly** [comment]
Thanks, I'll take another look.
