### ISSUE TITLE
Installed the package but unable to configure phpcs on PHPStorm.

### ISSUE THREAD

**Issue by joepages** [tighten/duster#115]
I've installed the package and it works great! 

I understand it comes with phpcs and other tools so I've trying to integrate those into my IDE (PHPStorm). 

I've configured phpcs but unabled to set/find the ruleset.xml file under the `vendor/tightenco` directory. 

One of the things I've tried was to copy the ruleset.xml under `https://github.com/tighten/duster/blob/2.x/standards/Tighten/ruleset.xml` but I believe that's not the idean solution I most likely have to be doing something wrong. 

Any help is much appreciated!

Thanks!
Jose 

![Screenshot 2023-07-12 at 10 20 03 PM](https://github.com/tighten/duster/assets/583979/2ebb4e08-a3f3-416e-af93-e9b3c0ebde88)
![Screenshot 2023-07-12 at 10 19 22 PM](https://github.com/tighten/duster/assets/583979/f33aabf7-3132-44c4-beb5-09a9ad039528)
![Screenshot 2023-07-12 at 10 19 13 PM](https://github.com/tighten/duster/assets/583979/228024a4-52b7-4fc1-96b0-6f19e9a6d2a6)

**Comment by driftingly** [comment]
Nope, I think that's on me.  I think I just need to allow those to be downloaded.  I'll let you know when that's fixed.  Thanks for reporting.

**Comment by joepages** [comment]
Thank you! Let me know if there’s anything I can do to speed that up :). This is a great package!

**Comment by driftingly** [comment]
The latest release now ships with the `standards` folder.

**Comment by joepages** [comment]
After a quick fire testing I’ve discovered that PHO_CodeSniffer doesn’t work correctly and doesn’t highlight the error while using the standards directory.

**Comment by driftingly** [comment]
@joepages you may need to tell PHP_CodeSniffer where to find the config:
https://github.com/squizlabs/PHP_CodeSniffer/wiki/Configuration-Options#setting-the-installed-standard-paths

**Comment by joepages** [comment]
I did that already. Working on custom xml but not when referencing the standards path to tightenco. Check attached screen shot. 
![Screenshot 2023-07-17 at 2 34 59 PM](https://github.com/tighten/duster/assets/583979/27c350bb-b3bb-4416-b811-b7c4d034e13e)

**Comment by driftingly** [comment]
I don't use PHPStorm, so it's harder for me to debug. Are you installing Duster globally?  Does the global composer vendor file contain all the files you need?  
When you run `phpcs -i` do you see the Tighten rule?  You might need to start testing outside of PHPStorm get more feedback.
