### ISSUE TITLE
Pint failing on Windows

### ISSUE THREAD

**Issue by nessimabadi** [tighten/duster#118]
Hi,

Pint is failing on Windows, there's an updated version (https://github.com/laravel/pint/releases/tag/v1.10.5) with the fix https://github.com/laravel/pint/pull/196

Since Pint hasn't been updated for Duster, Duster is failing on Windows.

Could Pint be updated?

Thanks for this amazing package.

**Comment by driftingly** [comment]
@nessimabadi Just updated to Pint v1.10.5
