### ISSUE TITLE
Duster fails on Windows after upgrading to version 2

### ISSUE THREAD

**Issue by mathiaswillburger** [tighten/duster#119]
I had a duster version 1 running for quite a while now without any issues.
After updating the package to the latest version (2.1.1) I get the following error executing ` ./vendor/bin/duster lint` (also with `fix`)

`Fatal error: Uncaught TypeError: trim(): Argument #1 ($string) must be of type string, bool given in phar://C:/projectpath/vendor/tightenco/duster/builds/duster/.box/src/Terminal.php:60
Stack trace:
#0 phar://C:/projectpath/vendor/tightenco/duster/builds/duster/.box/src/Terminal.php(60): trim(false)
#1 phar://C:/projectpath/vendor/tightenco/duster/builds/duster/.box/src/Terminal.php(31): HumbugBox436\KevinGH\RequirementChecker\Terminal::initDimensions()
#2 phar://C:/projectpath/vendor/tightenco/duster/builds/duster/.box/src/Printer.php(28): HumbugBox436\KevinGH\RequirementChecker\Terminal->getWidth()
#3 phar://C:/projectpath/vendor/tightenco/duster/builds/duster/.box/src/Checker.php(17): HumbugBox436\KevinGH\RequirementChecker\Printer->__construct(32, true)
#4 phar://C:/projectpath/vendor/tightenco/duster/builds/duster/.box/bin/check-requirements.php(22): HumbugBox436\KevinGH\RequirementChecker\Checker::checkRequirements()
#5 C:\xampp\htdocs\rma-api\vendor\tightenco\duster\builds\duster(12): require('phar://C:/xampp...')
#6 C:\xampp\htdocs\rma-api\vendor\bin\duster(119): include('C:projectpath...')
#7 {main}
  thrown in phar://C:/projectpath/vendor/tightenco/duster/builds/duster/.box/src/Terminal.php on line 60`

Using PHP 8.2, Laravel v8.83.27, Duster v2.1.1

**Comment by mathiaswillburger** [comment]
Still experiencing the same behavior after updating to Laravel 9 or 10

**Comment by driftingly** [comment]
I think this was a known issue with Box that has since been patch.
I've updated the dependencies. Can you update and try again?

**Comment by driftingly** [comment]
Yes, same issue - the update should work for you.
https://github.com/laravel/pint/issues/195

**Comment by mathiaswillburger** [comment]
confirmed, now it works. Thanks for the quick update!
