### ISSUE TITLE
Fixer does not fix TLint warning about global_namespace_import

### ISSUE THREAD

**Issue by machacekmartin** [tighten/duster#125]
After installing duster with no custom config whatsoever - the command `./vendor/bin/duster lint` successfully highlights errors regarding `global_namespace_import` rule (under _Linting using TLint_ section), but running `./vendor/bin/duster fix` does not actually fix these imports.

Example:
```php
Forms\Components\Fieldset::make('General information')
```
this is marked with **_Fully Qualified Class Names should only be used for accessing class names_** warning, but the `./vendor/bin/duster fix` command doesnt fix it. it just goes `LGTM!`

**Comment by driftingly** [comment]
TLint doesn't fix this linting issue.  I looked into it but couldn't find a way to do it reliably. There are too many edge cases having to do with name collisions. 

I'll leave this open for now as I consider a solution related to #124 where, if TLint discovers a listing issue, the fix command still fails.
