### ISSUE TITLE
adding more parameter to command

### ISSUE THREAD

**Issue by hairmenu** [tighten/duster#126]
i need to set --memory-limit 1G in order to have phpstan running but i could not figure how to do it as 
`"scripts": {
        "lint": {
            "phpstan": ["./vendor/bin/phpstan", "analyse --memory-limit 1G"]
        }
    }`
will return
`Command "analyse --memory-limit 1G" is not defined.  `

i could make it working by using a shell but it would be cool to be bale to add configuration in the duster.json line i think

**Comment by driftingly** [comment]
Hi @hairmenu 

You'll need to split out each parameter.  Try:

```
"scripts": { "lint": { "phpstan": ["./vendor/bin/phpstan", "analyse", "--memory-limit", "1G"] } }

```
