### ISSUE TITLE
Running duster via composer script causes event returned with error code 1

### ISSUE THREAD

**Issue by mathiaswillburger** [tighten/duster#130]
I run duster via a custom command configured in the `composer.json` file:

```
"scripts": {
    "format": [
      "vendor\\bin\\duster fix --dirty"
    ],
    "format:all": [
      "vendor\\bin\\duster fix"
    ]
  }
```

Since one of the latest versions however, the script stops somewhere when running the `Fixing using Pint` part with the following error:

`Script vendor\bin\duster fix handling the format:all event returned with error code 1`

However, when running the comment `vendor\\bin\\duster fix` manually in the console the process finishes as usual.
Anything I could additionally check to see where the error is coming from?

**Comment by driftingly** [comment]
You could try appending `-vvv` verbose flag to the command:
`vendor/bin/duster fix -vvv`

**Comment by mathiaswillburger** [comment]
Unfortunately, that starts dumping the whole source code to the console showing all changes when the Pint part is started, probably because TLint and PHP_Codesniffer applied their rules before. No obvious additional error is shown.

I still wonder why calling `vendor\\bin\\duster fix` directly runs fine but using a custom command returns error code 1.

**Comment by mathiaswillburger** [comment]
After using it for some while with the error, it just seems thats normal. No issues during formatting, everything works as expected except that at the end the error code 1 is shown.

**Comment by SimonMacIntyre** [comment]
This is also happening to us. It runs fine with no errors alone, but from composer invocation, it has this:
```
Script @php vendor/bin/duster -v fix handling the lint event returned with error code 1
```
