### ISSUE TITLE
PHPStorm plugin ?

### ISSUE THREAD

**Issue by superbiche** [tighten/duster#133]
Hi there, it's me again.  

I saw that you offer a PHPStorm plugin for Tlint.  

Do you plan doing the same for Duster (if you built the plugin yourselves and not a third-party I guess)? 
It would be great if we could at least use it as "External Formatter", so when using the Reformat file action, it uses Duster.  

If you're pretty sure you won't have time to do this, I'd like to give it a shot.  

Cheers,

**Comment by driftingly** [comment]
Hey there! Thanks for reaching out again. Unfortunately, I won't be working on a PHPStorm plugin for Duster as I don't use PHPStorm. However, you can definitely try using it as an external formatter and see how it works for you. If you face any issues, feel free to let me know and I'll try my best to help you out. Good luck!
