### ISSUE TITLE
[HELP] Construct class 

### ISSUE THREAD

**Issue by abkrim** [tighten/duster#144]
Hello.

Sorry for this issue. Really is a help.

```php
 public function __construct(
        public CoreProcess $coreProcess,
        public ?string $email = null,
        public ?string $emailCc = null,
        public ?string $emailBcc = null
    ) {
``` 

I don't see where is rule for this style.

When run duster fix, duster format to

```php
 public function __construct(public CoreProcess $coreProcess, public ?string $email = null, public ?string $emailCc = null, public ?string $emailBcc = null)
    {
``` 

I like my style because I think is correct more legible (not more 80 columns)

Is possible? 

I don't see the rule.

Best regards.

**Comment by driftingly** [comment]
Hi @abkrim,

When I run Duster against your example code I'm not getting the same long line result.
Are you running the latest version?
Do you have any existing configuration files in your repo for Pint, PHP_CodeSniffer, or PHP CS Fixer?

**Comment by abkrim** [comment]
Hi @driftingly 

I'm using versions : * v2.7.4, and Laravel Framework 10.48.4

Andyes

pint
```
{
    "preset": "laravel",
    "exclude": [
        "database",
        "elk",
        "config",
        "notas",
        "vendor"
    ]
}

```

The others no.

**Comment by driftingly** [comment]
I haven't been able to reproduce this issue. The constructor is always left as multi-lined:
```php 
 public function __construct(
        public CoreProcess $coreProcess,
        public ?string $email = null,
        public ?string $emailCc = null,
        public ?string $emailBcc = null
    ) {
```

I think there's still some other rule getting picked up to change it.

**Comment by abkrim** [comment]
No problem. Uninstall duster.

I like it, but with Pint, although I didn't have duster's skills, I didn't have these problems.

When I have some time, I will try again. It is not primary.

Thanks for your time.

**Comment by iAMUjjwal** [comment]
@driftingly @abkrim did u find out what was the issue? I am having the same issue and it is bit bothering.
