### ISSUE TITLE
Workflow's Fix and local fixes are different.

### ISSUE THREAD

**Issue by anuzpandey** [tighten/duster#154]
Hello.

Thank you for this package. But, I don't know what is wrong with my configuration, but, when I run `duster fix` in local dev, the formatting differs from the one that gets executed on github workflow.

Reference:
> With local `duster fix`

![image](https://github.com/tighten/duster/assets/25082225/43a7b6ed-ecf8-49ac-965b-ab24631aa913)

> With fixes from `github-actions`

![image](https://github.com/tighten/duster/assets/25082225/e883f0b8-bb1a-4fd7-9327-346c7641ad00)

--- 
I have a `pint.json` configuration.

https://gist.github.com/anuzpandey/ad0ba1483502440d7d63da0763484cf8

**Comment by driftingly** [comment]
Hi @anuzpandey, the most likely cause is different versions of Duster.
The Duster action will always use the latest version.
Try updating your local version:

```php
composer require tightenco/duster --dev
```

**Comment by anuzpandey** [comment]
@driftingly Thank you, updating local version fixed it.
Thank you so much.
