### ISSUE TITLE
Drop PHP-CS-Fixer?

### ISSUE THREAD

**Issue by mattstauffer** [tighten/duster#22]
It seems that PHPCBF has come a long way since Tighten decided to use PHPCS for sniffing and PHP-CS-Fixer for fixing.

Maintaining two standards has been a pain in the butt.

I've been hearing more and more people say that they've been happy with just PHPCS and PHPCBF.

Thoughts:

- Only upholding and supporting one standard would make Duster and Tighten projects much simpler
- Having our main sniffer and our main fixer be the same tool and standard would be _lovely_
- If we discover that there are lints that are missing from PHPCS/PHPCBF that PHP-CS-Fixer offer, I could be a part of helping making them available to the PHPCS world
- I hate XML for config and the fact that PHP-CS-Fixer uses PHP is one of the best things about it, but we can't pick a tool JUST because I hate XML

Any strong opinions?

**Comment by josecanhelp** [comment]
Once we have a standard dialed in, we won't be messing with it a whole lot. If the reason you're leaning to PHPCS is mainly because of XML, I personally don't think it's a good enough reason to use it. We can develop our standards in XML and rarely need to make changes.

Another idea (much like the Goku/Karabiner relationship) is to make a generation tool or use a YML/JSON/PHP -> XML generator tool to make it easy to develop the standards config.

**Comment by zoispag** [comment]
I saw your tweet, and even though I haven’t used it myself, (happy PHPCBF user here), I have bookmarked this for the longest time: https://tomasvotruba.com/blog/2017/05/03/combine-power-of-php-code-sniffer-and-php-cs-fixer-in-3-lines/
Maybe it can help you! :)

**Comment by schrapel** [comment]
I switched from using both to this which under the hood uses both

https://github.com/symplify/easy-coding-standard

**Comment by mattstauffer** [comment]
> Once we have a standard dialed in, we won't be messing with it a whole lot. If the reason you're leaning to PHPCS is mainly because of XML, I personally don't think it's a good enough reason to use it. We can develop our standards in XML and rarely need to make changes.

Totally agreed--I actually would lean *away* from PHPCS because of XML. Otherwise, I think PHPCS wins the day.

> Another idea (much like the Goku/Karabiner relationship) is to make a generation tool or use a YML/JSON/PHP -> XML generator tool to make it easy to develop the standards config.

Yah--it turns out the Easy Coding Standard mentioned above may actually be something just like that? But I have to dig into it more. Great thinking @josecanhelp!

Thanks @zoispag and @schrapel! I'm looking into easy coding standard. I think it's down to this question now:

Do we use PHPCS/PHPCBF or do we switch to Easy Coding Standard?

Upsides of ECS is it's PHP; downsides is it's another dependency in the chain, and I don't know yet whether it integrates with IDEs as easy/universally as PHPCS does.

**Comment by mattstauffer** [comment]
OK, I'm gonna drop PHP-CS-Fixer for starters. I'll dig into ECS when I get a chance. And I'm gonna see if we lose any fixers that we miss, and see if we figure out how to bring them back in pure PHP-CS.
