### ISSUE TITLE
Add security checks to duster

### ISSUE THREAD

**Issue by jonsugar** [tighten/duster#26]
I discovered [local-php-security-checker](https://github.com/fabpot/local-php-security-checker) and integrated it into my duster install. I wonder if it is the type of thing to consider for duster?

![image](https://user-images.githubusercontent.com/1974648/107805651-9094f780-6d5d-11eb-981f-a6787a18847d.png)

**Comment by mattstauffer** [comment]
Hm. My original thinking was that Duster was just about linting ("dust" the lint), but I do like the idea of adding something like this... perhaps optionally, though? The concern I have is that the bigger the package gets, the more likely one consumer will want _some but not all_ of the features it's offering.

But.. this is a really interesting idea anyway.

**Comment by driftingly** [comment]
If we add this, it will be through a config, as suggested in #29
