### ISSUE TITLE
End-user controlled ~/.duster extension point

### ISSUE THREAD

**Issue by jonsugar** [tighten/duster#29]
This issue overlaps/expands on #2, which was closed as it was too vague. 

Would a `~/.duster` directory be useful as a user-controlled extension point for Duster? Duster would look in  `~/.duster` for shell scripts named `lint`, `fix`, `lint-name`, or `fix-name` files and run them if appropriate. It would allow the user to add their own tooling easily.

**To be figured out**: what would happen if there was a lint-phpcs file in `~/.duster`? Should it be run as well as, or in place of, the one provided in the main Duster installation?

### Use case

I'm pretty much using TLint and Tightens PHPCS as my baselines but I'd like to use Duster to run ESLint, the PHP security check and node audits as well. Previously, I had hacked the Duster installation, adding `lint-eslint` in `vendor/tightenco/duster/bin/actions`, and this worked well but my changes were overridden on composer update.

@mattstauffer, Re: #1 and #26, I totally get that you are not decided on whether to add security checks or ESLint yet but an extension mechanism like this would allow flexibility for the end-user. It would also help when spiking a new lint before possible inclusion as a main standard.

**Comment by mattstauffer** [comment]
I think this would have to be in the project directory, not in the user directory. But I do really like the idea!

And I do think we could use the custom scripts to overwrite Duster-included scripts.

**Comment by jonsugar** [comment]
Oooh. Project directory. Even better!

**Comment by driftingly** [comment]
This is coming as part of PR #47.

```json
{
    "scripts": {
        "lint": {
            "phpstan": ["./vendor/bin/phpstan", "analyse"]
        }
    }
}
```

Duster will pick these up automatically when running `--lint` or `--fix` or you can provide the tools and order to Duster: 

```bash
./vendor/bin/duster --lint --using="phpstan,tlint,pint"
```

**Comment by mattstauffer** [comment]
Fantastic! Thanks @driftingly!
