### ISSUE TITLE
Duster execution error

### ISSUE THREAD

**Issue by vincenzotecnology** [tighten/duster#48]
Hello everybody.

I'm starting with duster, I installed it in my application as explained on github, but when I run any duster action in the terminal, I get an error, like the print below:

![image](https://user-images.githubusercontent.com/100493797/208318341-3028db84-e857-4505-b220-ce91f75741e1.png)

Already tried :
.\duster github-actions
It gives error saying it is not a cmlet

.\vendor\bin\duster github-actions
says there is no file or directory.

![image](https://user-images.githubusercontent.com/100493797/208318456-c77dd352-f054-4cc3-aaf2-3b0e6b5af5aa.png)

can you help me?

**Comment by driftingly** [comment]
Hello, sorry you're having issues.  I'm unfamiliar with Laragon and Windows development, but I will try my best to help. 

It looks like the proxy created by composer is using the incorrect slashes.  I suspect this would be the case for all the proxies in `.\vendor\bin`.  Composer may need additional steps to be setup on [Windows](https://getcomposer.org/doc/00-intro.md#installation-windows).

You could also try running the bin from `.\vendor\tightenco\duster\bin\duster`:

```bash
.\vendor\tightenco\duster\bin\duster github-actions
```

**Comment by driftingly** [comment]
@vincenzotecnology Feel free to reopen if you are still having issues.
