### ISSUE TITLE
Whitespace around re-ordered class properties and constants is incorrect

### ISSUE THREAD

**Issue by bakerkretzmar** [tighten/duster#49]
Anecdotally I'm noticing that this:

```php
class Foo
{
    protected $foo = 'bar';
    public $bar = 'baz';
    public const FOO = 'bar';
    protected $bar = 'baz';
}
```

Is formatted to this:

```php
class Foo
{
    public const FOO = 'bar';
    public $bar = 'baz';

    protected $foo = 'bar';
    protected $bar = 'baz';
}
```

The whitespace around/between properties and constants that get reordered isn't always consistent. Happy to work on this myself when I have time next week.

**Comment by driftingly** [comment]
The spacing is from TLint's `OneLineBetweenClassVisibilityChanges`

> Class members of differing visibility must be separated by a blank line

**Comment by bakerkretzmar** [comment]
Sorry I should have been more specific—what's weird to me is that there _isn't_ whitespace added after the `public CONST`. I would have expected either of these instead:

```php
class Foo
{
    public const FOO = 'bar';
    public $bar = 'baz';
    protected $foo = 'bar';
    protected $bar = 'baz';
}
```

```php
class Foo
{
    public const FOO = 'bar';

    public $bar = 'baz';

    protected $foo = 'bar';
    protected $bar = 'baz';
}
```

**Comment by bakerkretzmar** [comment]
Basically I want the formatter to fix _all_ the whitespace for me, including in between `const`s and properties 😂

**Comment by driftingly** [comment]
Right now, `OneLineBetweenClassVisibilityChanges` doesn't distinguish between const/properties, it only looks at visibility changes.  I think we would need an additional linter/formatter for class attribute groups, something like `OneLineBetweenClassAttributeGroups`.

Pint's Laravel preset uses `class_attributes_separation` to add a blank line between most:

```php
'class_attributes_separation' => [
    'elements' => [
        'const' => 'one',
        'method' => 'one',
        'property' => 'one',
        'trait_import' => 'none',
    ],
],
```

We overwrite this to only require a blank line between `method`.  I'm wondering if we should follow the laravel convention on this as well.

```php
class Foo
{
    public const FOO = 'bar';

    public $bar = 'baz';

    protected $foo = 'bar';

    protected $bar = 'baz';
}
```

**Comment by driftingly** [comment]
Fixed in https://github.com/tighten/tlint/pull/369
