### ISSUE TITLE
Possibly add something that makes GH actions easier to set up?

### ISSUE THREAD

**Issue by mattstauffer** [tighten/duster#5]

**Comment by Gummibeer** [comment]
There aren't re-usable workflows - the only thing you could do here would be a docker container.
Something I have for @Astrotomic is a node.js snippet that copies all metafiles to all repos.
https://github.com/Astrotomic/.github

**Comment by mattstauffer** [comment]
@Gummibeer Thanks, so I guess here's what I meant:

```bash
./vendor/bin/duster init ghactions
```

Which would then stub in `.github/workflows/lint.yml` or something similar, which would run all the linters. 

I think that's pretty doable.. I assume what you're suggesting is something similar, right?

**Comment by Gummibeer** [comment]
Yes. If you have the stub in the package it's even easier as you don't have to go via GH API.
So it's a simple copy'n'paste.

**Comment by mattstauffer** [comment]
@Gummibeer Thanks my friend!
