### ISSUE TITLE
Override class member ordering in test classes

### ISSUE THREAD

**Issue by bakerkretzmar** [tighten/duster#50]
Not sure if this is a bug or a feature request—[`setUp()` and `tearDown()` are `protected`](https://phpunit.readthedocs.io/en/9.5/fixtures.html#fixtures-examples-stacktest-php) but should (I think?) be at the top of the test class for clarity. Thoughts?

**Comment by driftingly** [comment]
I agree with this.

**Comment by driftingly** [comment]
There's a `phpunit` parameter we can use:
https://cs.symfony.com/doc/rules/class_notation/ordered_class_elements.html

Uses the following order:

```
'setupbeforeclass' => 1,
'dosetupbeforeclass' => 2,
'teardownafterclass' => 3,
'doteardownafterclass' => 4,
'setup' => 5,
'dosetup' => 6,
'assertpreconditions' => 7,
'assertpostconditions' => 8,
'teardown' => 9,
'doteardown' => 10,
```

I'll look at updating this tomorrow.
