### ISSUE TITLE
duster with sail ?

### ISSUE THREAD

**Issue by Grazulex** [tighten/duster#91]
Hello,

I used Sail to run localy my projet.
I have install your package but I can't not run duster with Sail.... I try "./vendor/bin/sail duster lint" but is not working : "No such command: duster"

**Comment by m4tr1ck** [comment]
Maybe try `./vendor/bin/sail ./vendor/bin/duster` duster is not a package that includes default commands for artisan and a PHP in the root structure of your project so you have to execute it like composer or other commands.

**Comment by tonysm** [comment]
@Grazulex looks like you were trying to run Duster as it was a default Sail script. That's not the case, as the Sail scripts are hard-coded (see [here](https://github.com/laravel/sail/blob/1.x/bin/sail)).

You can do what @m4tr1ck did but you'd need to prefix the duster phar execution with `php`, something like:

```bash
./vendor/bin/sail php ./vendor/bin/duster
```

Alternatively, Sail has a `bin` [script](https://github.com/laravel/sail/blob/1.x/bin/sail#L211) that eases execution of package binaries, so you do the same thing like this:

```bash
./vendor/bin/sail bin duster
```

Either way should work.

Closing the issue for now, but let us know if you run into any other issue.

**Comment by driftingly** [comment]
Added to the readme https://github.com/tighten/duster#usage-with-sail
Thanks @Grazulex for the question and @m4tr1ck and @tonysm for the help.
