### ISSUE TITLE
Graceful dirty linting exit

### ISSUE THREAD

**Issue by hylke94** [tighten/duster#92]
Would it be possible to gracefully kill the dirty linting script when there are no dirty files in your repository, with an extra flag/option?

I wanna add Duster as pre-commit hook to my project. With the dirty flag enabled, to not scan my complete project all the time. But at the moment, the command (and thus my hook) fails when there are no dirty PHP-files, when I only update the readme for example. So my question is, can we add an extra flag to the lint command, which will show the "no dirty flags" message (maybe as info instead of error in this case), but exits with exit code 0?

**Comment by driftingly** [comment]
I will tag this as a bug because this is the expected behaviour.

**Comment by hylke94** [comment]
Can't wait for the fix. Used Duster only for one night on a private project yet, but I'm sold :wink:

**Comment by driftingly** [comment]
@hylke94 give 1.1.1 a try and let me know if that resolves this issue.

**Comment by hylke94** [comment]
> @hylke94 give 1.1.1 a try and let me know if that resolves this issue.

It works! Thank!
