### ISSUE TITLE
Duster ignring configuration added in .php-cs-fixer.dist.php

### ISSUE THREAD

**Issue by HiKanav** [tighten/duster#94]
Thanks for building this tool. 

I wanted to disable the `no_superfluous_phpdoc_tags` rule of PhpCsFixer.

As per the docs, I created a `.php-cs-fixer.dist.php` file in the root of the project, with the contents from [Duster's .php-cs-fixer.dist.php](https://github.com/tighten/duster/blob/main/standards/.php-cs-fixer.dist.php), making it something like:

```
<?php

use App\Fixer\ClassNotation\CustomControllerOrderFixer;
use App\Fixer\ClassNotation\CustomOrderedClassElementsFixer;
use App\Fixer\ClassNotation\CustomPhpUnitOrderFixer;
use App\Support\PhpCsFixer;
use PhpCsFixer\Config;

return (new Config())
    ->setFinder(PhpCsFixer::getFinder())
    ->setUsingCache(false)
    ->registerCustomFixers([
        new CustomControllerOrderFixer(),
        new CustomOrderedClassElementsFixer(),
        new CustomPhpUnitOrderFixer(),
    ])
    ->setRules([
        'Tighten/custom_controller_order' => true,
        'Tighten/custom_ordered_class_elements' => [
            'order' => [
                'use_trait',
                'case',
                'property_public_static',
                'property_protected_static',
                'property_private_static',
                'constant_public',
                'constant_protected',
                'constant_private',
                'property_public',
                'property_protected',
                'property_private',
                'construct',
                'method:__invoke',
                'method_public_static',
                'method_protected_static',
                'method_private_static',
                'method_public',
                'method_protected',
                'method_private',
                'magic',
            ],
        ],
        'Tighten/custom_phpunit_order' => true,
        'no_superfluous_phpdoc_tags' => false,
    ]);
```

However, `./vendor/bin/duster fix` or `./vendor/bin/duster lint` seems to ignore the ` 'no_superfluous_phpdoc_tags' => false`, or perhaps ignoring the `.php-cs-fixer.dist.php` file completely.

Am I missing something? Do I need to specify the path of `.php-cs-fixer.dist.php` anywhere so Duster picks up the customization?

**Comment by driftingly** [comment]
This rule is part of [Pint](https://github.com/laravel/pint/commit/7a0793086b861e394a4e9c90c8d10b95ac2111ca).
Since Pint doesn't support supplying custom fixers I include PHP-CS-Fixer to run the `Custom*` rules.    

To remove this rule you'll have to follow the Pint instructions.
