### ISSUE TITLE
Failed on docblock @param

### ISSUE THREAD

**Issue by nashsaint** [tighten/duster#95]
I do not understand why having a @param like this fails?
<img width="448" alt="image" src="https://user-images.githubusercontent.com/1625528/225631155-9082de2a-09f9-4cab-bf32-14756681bdb5.png">

**Comment by mattstauffer** [comment]
If you look at the output from the `duster` run, you'll gather helpful information such as:

- Which linter is showing that error
- Which error is coming up from that linter

I added the above code to my project, and here's what I saw:

<img width="1458" alt="image" src="https://user-images.githubusercontent.com/151829/225760260-cf240a86-9c72-46a0-bbef-2a73c0d2536d.png">

As you can see, it's Pint throwing the error, and it's throwing three errors:

`no_superfluous_phpdoc_tags, no_trailing_whitespace_in_comment, global_namespace_import`

So your `@param` is likely triggering `no_superfluous_phpdoc_tags`.

**Comment by driftingly** [comment]
Yep, if you would like to remove this option, you'll need to follow the [Pint](https://github.com/tighten/duster#pint) customization instructions. 

Copy the Duster Pint config to your project's root and add:
```
 "no_superfluous_phpdoc_tags": false
```
