### ISSUE TITLE
--dirty does not work on Windows

### ISSUE THREAD

**Issue by Rigby90** [tighten/duster#96]
Duster appears to make use of the Project & GitPathsRepository classes from Laravel Pint to build up the array of 'dirty' files from Git.

However as Duster pins Laravel Pint to version 1.5 it does not include the fix from Pint which resolves the --dirty flag working on Windows due to the differences in slashes in directory paths.

https://github.com/laravel/pint/pull/150
https://github.com/laravel/pint/releases/tag/v1.6.0

Unfortunately this doesn't look like a straight forward change from 1.5 to 1.6 due to the fact that Laravel Pint requires both PHP 8.1 (at a minimum) and Laravel Zero 10.

Unsure whether it would be easier in the short term to bring the GitPathRepository class into Duster itself to resolve the issue until such a time that Duster is updated in line with Laravel Pint.

**Comment by driftingly** [comment]
Yeah, that makes sense.  I've also considered updating Duster to Zero 10 and downgrading PHP when releasing.

**Comment by driftingly** [comment]
@Rigby90 I just released version 2.0, which drops support for older versions of PHP to allow Duster to update Pint.
